### ISSUE TITLE
'exa' command not found -- but it is installed

### ISSUE THREAD

**Issue by gonzus** [zap-zsh/exa#8]
This happens on a Mac M1 laptop.

When I open a new terminal I get this error:
```
ERROR: 'exa' command not found
```
But the command is already installed:
```
$ which exa
/Users/gonzo/homebrew/bin/exa
⚡ 13:16 Thu 04/May gonzo@gonzo-mbp ~ 

$ exa *.txt
fedora.txt  gonzo.txt  lan.txt  notes.txt  sean.txt  valentin.txt
```

**Comment by kuckjwi0928** [comment]
When using homebrew, it seems that the brew shell must be applied to the .zshrc file first for it to work.

```shell
eval $(/opt/homebrew/bin/brew shellenv)
...
plug "example/plugin"
```

**Comment by mamaraddio** [comment]
Unfortunately I can't test it. @gonzus could you confirm that @kuckjwi0928 's solution works for you?

**Comment by gonzus** [comment]
Yes, this solves the problem. Thanks @kuckjwi0928 !
